repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
      args: [--assume-in-merge]
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=auto]
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.33.0
    hooks:
    - id: eslint
